config/routes.rb
StackOverflow::Application.routes.draw do

  get 'sessions/logout' => 'sessions#destroy', as: :logout
  post 'sessions/new' => 'sessions#new', as: :login
  post 'search' => 'welcome#search'

  post 'questions/:id' => 'questions#vote', as: :vote

  resources :users
  resources :questions do
    resources :answers
  end

  get '/comments/:answer_id' => 'comments#new', as: :new_comment
  post '/comments/:user_id/:answer_id' => 'comments#create', as: :comments
  resources :tags
  resources :comments
  resources :badges

  root to: 'welcome#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :q_title, :q_content, :user_id, :votes

  belongs_to :user
  has_many :answers
  has_many :question_tags
  has_many :tags, through: :question_tags

  validates :q_title, presence: :true
  validates :q_content, presence: :true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order("votes ASC")
  end

  def create
    @question = Question.new(params[:question])
    @tags = params[:tags][:t_content].scan(/(\w+)/)
    if current_user
      @question.user = current_user
      if @question.save
        @tags.each do |tag|
          @question.tags << Tag.where(t_content: tag[0]).first_or_create
        end
        redirect_to root_path
      else
        render '/questions/new'
      end
    else
      redirect_to new_user_path
    end
  end

  def new
    if current_user
    @question = Question.new
    else
      redirect_to new_user_path
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])

    @tag = Tag.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    redirect_to user_path
  end

  def destroy
    @question = Question.find(params[:id])
    Answer.delete_all(question_id: @question.id)
    @question.destroy
    redirect_to user_path
  end

  def vote
      @question = Question.find(params[:id])
      puts params
      puts "----------------------------------------------------"
      passed_data = params.first[0]
      if request.xhr?
        @question.update_attributes(votes: @question.votes += passed_data.to_i)
        # render :nothing => true
        # puts "-----------------------------------------------------------"
        # puts @question.votes.to_json
        render json: @question.votes.to_json
      end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/edit.html.erb
<h1 class="welcome">Edit your question</span></h1>

<container class="left" id="edit_question">

<%= form_for @question do |f| %>
  <%= f.label :q_title, "Title" %><br/>
  <%= f.text_field :q_title, placeholder: 'title' %><br>
  <%= f.label :q_content, "Question" %><br/>
  <%= f.text_area :q_content, placeholder: 'content', size: "60x12" %><br>
  <%= fields_for :tags do |tag_field| %>
      <%= tag_field.label :t_content, "Tags" %>
      <%= tag_field.text_field :t_content, placeholder: 'tags' %>
    <% end %><br><br>
  <%= f.submit %>
<% end %>

</container>

app/views/questions/index.html.erb
<% if current_user %>
  <%= current_user.email %>
<% end %>

app/views/questions/new.html.erb
<h1 class="welcome">Ask a question</span></h1>

<container class="left" id="edit_question">

<%= form_for @question do |f| %>
  <% @question.errors.each do |attr, msg| %>
  <p><%= attr %><%= msg %></p>
  <% end %>
  <p>
    <%= f.label :q_title, "Title" %><br/>
    <%= f.text_field :q_title, placeholder: 'title' %><br>
    <%= f.label :q_content, "Question" %><br/>
    <%= f.text_area :q_content, placeholder: 'content', size: "60x12" %><br>
    <%= fields_for :tags do |tag_field| %>
      <%= tag_field.label :t_content, "Tags" %>
      <%= tag_field.text_field :t_content, placeholder: 'tags' %>
    <% end %>
    <%= f.submit %>
  </p>
<% end %>
</container>

app/views/questions/show.html.erb
<container class="display_questions" id="display_questions">
<div id="show_question">
<b><%= @question.q_title %></b><br><br>
<%= @question.q_content %></div><br><br>


<% @question.answers.each do |answer| %>
<p>
  <%= answer.a_content %><br>
  <%= answer.user.email if @question.user %>
  <%= time_ago_in_words(answer.created_at) %> ago
  	<div style="color:darkmagenta;font-size:12px;margin-left:20px;width:400px;">
  		<% answer.comments.each do |comment| %>
  		<%= comment.c_content %><br/>
  		<span style="color:black"> <%= User.find(comment.user_id).email %>
  		  <%= time_ago_in_words(comment.created_at) %> ago</span>
		<% end %>
  	</div>
</p>
<p id="add_comment_link"><%= link_to "Add Comment", new_comment_path(answer) %></p>
<% end %>

<%= form_for([@question, @answer]) do |f| %><br>
 <b><%= f.label :a_content, "Your Answer:" %><br/><b>
  <%= f.text_area :a_content, placeholder: 'Type your response...', size: "60x12" %><br>
 <%= f.submit %>
<% end %>
</container>