config/routes.rb
StackOverflow::Application.routes.draw do

  get 'sessions/logout' => 'sessions#destroy', as: :logout
  post 'sessions/new' => 'sessions#new', as: :login
  post 'search' => 'welcome#search'

  post 'questions/:id' => 'questions#vote', as: :vote

  resources :users
  resources :questions do
    resources :answers
  end

  get '/comments/:answer_id' => 'comments#new', as: :new_comment
  post '/comments/:user_id/:answer_id' => 'comments#create', as: :comments
  resources :tags
  resources :comments
  resources :badges

  root to: 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer_id, :a_content, :user_id, :question_id, :votes
  belongs_to :user
  belongs_to :question
  has_many :comments


  validates :a_content, presence: :true
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base

belongs_to :user
attr_accessible :provider, :uid, :presence => true

def self.find_or_create(auth_hash)
  unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    user = User.create :name => auth_hash["user"]["name"], :email => auth_hash["user"]["email"]
    auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
 
  auth
end
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	attr_accessible :user_id

	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :answer_id, :user_id, :c_content

	belongs_to :user
	belongs_to :answer
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :file, :user_id

  belongs_to :user
  mount_uploader :file, Uploader
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :q_title, :q_content, :user_id, :votes

  belongs_to :user
  has_many :answers
  has_many :question_tags
  has_many :tags, through: :question_tags

  validates :q_title, presence: :true
  validates :q_content, presence: :true
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
  attr_accessible :question_id, :tag_id

  belongs_to :tag
  belongs_to :question
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :t_content

  has_many :question_tags
  has_many :questions, through: :question_tags

  validates :t_content, presence: :true
end

app/models/uploader.rb
class Uploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :file

  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  process resize_to_limit: [800, 800]

  version :thumb do
    process resize_to_fill: [250, 250]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :date_of_birth, :email, :password, :password_confirmation, :website, :photo, :current_city, :interests, :name

  validates :email, :presence =>true,
                    :uniqueness=>true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, on: :create

  validates :password, :presence =>true, on: :create
  validates :password, length: { minimum: 6 , message: "Password needs to be at least 6 characters" }, on: :create
  validates_confirmation_of :password, on: :create
  validates :password_confirmation, presence: true, on: :create 


  has_many :questions
  has_many :answers
  has_many :comments
  has_many :badges

  has_one :photo

  has_secure_password
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
     @question = Question.find(params[:question_id])
     @answer = Answer.new
  end


  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params[:answer])
    @answer.question_id = @question.id

    if current_user
      @answer.user = current_user
      if @answer.save
        redirect_to question_path(@question, @answer)
      else
        render '/question'
      end
    else
      redirect_to new_user_path
    end
  end


  def show
    @question = Question.find(params[:question_id])
    @answer = Answer.new(params[:answer])
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to user_path
  end

  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update_attributes(params[:answer])
    redirect_to user_path
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
	def show
		@badge = badge.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
	end
	
	def new
		if current_user
		@answer = Answer.find(params[:answer_id])
		@comment = Comment.new
		else
		redirect_to new_user_path
		end
	end
	
	def edit
		@comment = Comment.find(params[:id])	
	end
	
	def create
		@answer = Answer.find(params[:answer_id])
		@question = Question.find(@answer.question_id)
		@comment = Comment.new(user_id: current_user.id, answer_id: @answer.id, c_content:(params[:comment][:c_content]))
		if @comment.save
		 redirect_to question_path(@question)
		else
			redirect_to user_path(current_user)
		end
	end
		
 	def update
    @comment = Comment.find(params[:id])
    @comment.update_attributes(params[:comment])
    redirect_to user_path
   end

	def destroy
		@comment = Comment.find(params[:id])
    	@comment.destroy
    	redirect_to user_path
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @user = User.find_by_email(params[:session][:email])
      p @user
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def create
    auth_hash = request.env['omniauth.auth']
    @authorization = Authorization.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    if @authorization
      render :text => "Welcome back #{@authorization.user.name}! You have already signed up."
    else
      user = User.new :name => auth_hash["user"]["name"], :email => auth_hash["user"]["email"]
      user.authorizations.build :provider => auth_hash["provider"], :uid => auth_hash["uid"]
      user.save
  
      render :text => "Hi #{user.name}! You've signed up."
    end
  end 

  def destroy
    session.clear
    redirect_to root_path
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    # render params[:id].inspect
    @tag = Tag.find(params[:id])

    @questions = @tag.questions
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if params[:photo]
      @user.photo = Photo.create(file: params[:photo][:file])
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
    @questions = Question.where(user_id: @user.id)
    @answers = Answer.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if params[:photo]
      @user.photo = Photo.create(file: params[:photo][:file])
    end
    redirect_to user_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @questions = Question.order("votes DESC")
  end
  
  def search
  		p params
  		@var = params[:search_term]
        @questions = Question.where('q_title LIKE ?', "%#{@var}%").all
		
        render "search", layout: false
        
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/edit.html.erb
<h1>Edit your answer</h1>

<%= form_for ([@question, @answer]) do |f| %>
  <%= f.text_area :a_content, placeholder: 'Type your response...', size: "60x12" %><br>
  <%= f.submit %>
<%end%>

app/views/badges/index.html.erb
<h1 class="welcome">Badges</h1>
<div>
<container id="badge_container1" class="explain_badges">
	<h3>The Unicorn Badge</h3>
	<span class="badge"><%= image_tag "unicorn_badge.jpg" %></span><br><br>
	<span>Awarded to users who ask at least one question</span>
</container>
<container id="badge_container2" class="explain_badges">
	<h3>The America Badge</h3>
  <span class="badge"><%= image_tag "eagle_badge.jpg" %></span><br><br>
  <span>Awarded to all users upon creating an account</span>
</container>
<container id="badge_container3" class="explain_badges">
  <h3>The Cartman Badge</h3>
  <span class="badge"><%= image_tag "cartman_badge.png" %></span><br><br>
  <span>Awarded to users who have answered at least one question</span><br>
</container>
</div>

<p class="edit_links" id="back_profile"><%= link_to "Back to your profile", user_path(current_user.id) %></p>

app/views/comments/create.html.erb
yaya

app/views/comments/edit.html.erb
<h1>Edit comment..<h1>

<%= form_for @comment do |f| %>
  <%= f.text_area :c_content, placeholder: 'content', size: "60x12" %><br>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>Comment on..</h1>
<%= @answer.a_content %> 

<h3>Your Comments..</h3>
<%= form_for @comment, url: comments_path(current_user, @answer)  do |f| %>
<%= f.text_area :c_content , size: "60x12"%><br/>
<%= f.submit %>
<% end %>

app/views/tags/_tag_button.html.erb
<div class="tags">
  <%= link_to tag.t_content, tag_path(tag) %>
</div>

app/views/tags/show.html.erb
<h1>Related Questions for Tag</h1>


<table>
      <% @questions.each do |question| %>
        <tr><td><%= link_to question.q_title, question_path(question) %> </td></tr>
      <% end %>
</table>

app/views/welcome/index.html.erb
<h2>Top Questions:</h2>
<table>

    <% @questions.each do |question| %>
    <tr>
      <td id="votes_buttons" style="width:75px;">
        <%= link_to image_tag('http://upload.wikimedia.org/wikipedia/en/7/72/Dark_Green_Arrow_Up.png'), vote_path(question), html_options = { class: "increase-vote", data: 1, remote: true } %>
        <div style="float:left;clear:left;text-align:center"><%= question.votes %></div>
        <%= link_to image_tag('http://images2.wikia.nocookie.net/__cb20090706115259/manchesterunited/images/thumb/1/1c/Red_Arrow_Down.png/480px-Red_Arrow_Down.png'), vote_path(question), html_options = { class: id="decrease-vote", data: -1, remote: true } %>
      </td>

      <td id="number_answers"><%= question.answers.count %> answers</td>
      <td class="index_question"><b id="q_titles"><%= link_to question.q_title, question_path(question) %></b></td>
      <td><%= question.q_content %><br>
          <% question.tags.each do |tag| %>
            <%= render partial: "tags/tag_button", locals: {tag: tag} %>
          <% end %>
      </td>
      <td><b><%= distance_of_time_in_words_to_now(question.created_at) %> ago</b></td>
      </tr>
    <% end %>

</table>

app/views/welcome/search.html.erb
<h2>Top Questions:</h2>
<table>

    <% @questions.each do |question| %>
    <tr>
      <td><%= question.votes %> votes</td>
      <td><%= question.answers.count %> answers</td>
      <td><b><%= link_to question.q_title, question_path(question) %></b></td>
      <td><%= question.q_content %><br>
          <% question.tags.each do |tag| %>
            <%= render partial: "tags/tag_button", locals: {tag: tag} %>
          <% end %>
      </td>
      <td><b><%= distance_of_time_in_words_to_now(question.created_at) %> ago</b></td>
      </tr>
    <% end %>

</table>