config/routes.rb
StackOverflow::Application.routes.draw do

  get 'sessions/logout' => 'sessions#destroy', as: :logout
  post 'sessions/new' => 'sessions#new', as: :login
  post 'search' => 'welcome#search'

  post 'questions/:id' => 'questions#vote', as: :vote

  resources :users
  resources :questions do
    resources :answers
  end

  get '/comments/:answer_id' => 'comments#new', as: :new_comment
  post '/comments/:user_id/:answer_id' => 'comments#create', as: :comments
  resources :tags
  resources :comments
  resources :badges

  root to: 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :date_of_birth, :email, :password, :password_confirmation, :website, :photo, :current_city, :interests, :name

  validates :email, :presence =>true,
                    :uniqueness=>true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, on: :create

  validates :password, :presence =>true, on: :create
  validates :password, length: { minimum: 6 , message: "Password needs to be at least 6 characters" }, on: :create
  validates_confirmation_of :password, on: :create
  validates :password_confirmation, presence: true, on: :create 


  has_many :questions
  has_many :answers
  has_many :comments
  has_many :badges

  has_one :photo

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if params[:photo]
      @user.photo = Photo.create(file: params[:photo][:file])
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
    @questions = Question.where(user_id: @user.id)
    @answers = Answer.where(user_id: @user.id)
    @comments = Comment.where(user_id: @user.id)
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    if params[:photo]
      @user.photo = Photo.create(file: params[:photo][:file])
    end
    redirect_to user_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>User Page</h1>

app/views/users/edit.html.erb
<h2 class="welcome">Edit your profile</h2>

<container class="left", id="edit_profile">
<%= form_for @user, html: { multipart: true } do |f| %>
	<%= f.label :name, "Name:" %>
  	<%= f.text_field :name %><br><br>
  <%= f.label :current_city, "Current city:" %>
    <%= f.text_field :current_city %><br><br>
  <%= f.label :website, "Website:" %>
 		<%= f.text_field :website %><br><br>
  <strong>Change your profile picture:
    <%= fields_for :photo, @user.photo do |photo_fields|%>
    <%= photo_fields.file_field :file %>
  <% end %></strong><br><br>
 	<%= f.label :date_of_birth, "Date of birth:" %>
  		<%= f.date_select :date_of_birth, :start_year => 1945 %><br><br>
  <%= f.label :interests, "Interests:" %><br>
  	<%= f.text_area :interests, size: "60x12" %><br>
  
  <%= f.submit %>

	<% end %>
</container>

app/views/users/new.html.erb
<h1 class="welcome">Please sign up or log in </h1>

<container class="left" id="signup">
<%= form_for @user, html: { multipart: true } do |f| %>
  <p><%= f.text_field :email, placeholder: "email" %></p>
  <p><%= f.password_field :password, placeholder: "password" %></p>
  <p><%= f.password_field :password_confirmation, placeholder: "password confirmation" %></p>
  <p>Upload a profile picture:</p>
  <%= fields_for :photo, @user.photo do |photo_fields|%>
    <p><%= photo_fields.file_field :file %></p>
  <% end %>
  <p><%= f.submit "Create" %></p>

<% end %>
</container>

app/views/users/show.html.erb
<h1 class="welcome">Welcome back, 
	<% if @user.name %>
			<%= @user.name %>!
	<% else %>
			<%= @user.email %>!
	<% end %>
</h1>

<container class="left">
<div id="personal_info">
<div id="photo">
  <% if @user.photo %>
    <%= image_tag(@user.photo.file.url(:thumb)) %>
  <% else %>
    <%= image_tag "silhouette.jpg" %>
  <% end %>
</div>
  <h2 id="personal_info_title">Personal information</h2>
  <strong>Website:</strong> <%= @user.website %><br><br>
  <strong>Birthday:</strong> <%= @user.date_of_birth %><br><br>
  <strong>Current city:</strong> <%= @user.current_city %><br><br>
  <strong>Interests:</strong> <%= @user.interests %><br><br>
<div id="edit_profile_link"><%= link_to "Edit your profile", edit_user_path(@user) %></div>
</div>
</container>

<container id="right">
<div id="your_stuff">

  <h2>Your badges:</h2>
  <% if @user.questions.count >= 1 %>
    <span class="badge"><%= image_tag "unicorn_badge.jpg" %></span>
  <% end %>

    <span class="badge"><%= image_tag "eagle_badge.jpg" %></span>

  <% if @user.answers.count >= 1 %>
    <span class="badge"><%= image_tag "cartman_badge.png" %></span><br><br>
  <% end %>
   <span class="delete_links"><%= link_to "Learn about badges", badges_path %></span><br>
  <h2>Your questions:</h2>
    <% @questions.each do |question| %>
    <strong><%= question.q_title %></strong><br/>
    <%= question.q_content %><br/>
    <% question.tags.each do |tag| %>
        <%= render partial: "tags/tag_button", locals: {tag: tag} %>
        <% end %>
        <br>

    <span class="delete_links">
    <%= link_to "Delete", question_path(question), method: :delete,
                                                    confirm: "Are you sure?" %></span>
    <span class="edit_links">
    <%= link_to "Edit", edit_question_path(question) %></span><br>
  <% end %>


    
      <h2>Your answers:</h2>
    <% @answers.each do |answer| %>
    <%= answer.a_content %><br/>

    <span class="delete_links">
    <%= link_to "Delete", question_answer_path(answer.question_id, answer), method: :delete,
                            confirm: "Are you sure?" %></span>
    <span class="edit_links">
    <%= link_to "Edit", edit_question_answer_path(answer.question_id, answer) %></span><br><br><br>
    <% end %>

    
    
      <h2>Your Comments:</h2>
    <% @comments.each do |comment| %>
    <%= comment.c_content %><br/>

    <span class="delete_links">
    <%= link_to "Delete", comment_path(comment.id), method: :delete,
                            confirm: "Are you sure?" %></span>
    <span class="edit_links">
    <%= link_to "Edit", edit_comment_path(comment.id) %></span><br><br><br>
    <% end %>

</div>
</container>